- name: Copy file mongodb.repo config
  ansible.builtin.copy:
    src: mongodb.repo
    dest: /etc/yum.repos.d/mongodb.repo

- name: Installing mongodb server
  ansible.builtin.yum:
    name: mongodb-org
    state: installed

- name: update listen address
  ansible.builtin.replace:
    path: /etc/mongod.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: Start service mongod, if not started
  ansible.builtin.systemd:
    name: mongod
    state: restarted
    enabled: yes
