- name: parameters
  hosts: localhost
  connection: local
  tasks:
    - name: Create or update key/value pair in AWS SSM parameter store
      community.aws.aws_ssm_parameter_store:
        name: "{{ item.name }}"
        value: "{{ item.value }}"
        region: us-east-1
      loop:
        - {name: "dev.cart.REDIS_HOST", value: "redis-dev.chandupcs.online"}
        - {name: "dev.cart.CATALOGUE_HOST", value: "catalogue-dev.chandupcs.online" }
        - {name: "dev.cart.CATALOGUE_PORT", value: "80" }
        - {name: "dev.catalogue.MONGO", value: "true" }
        - {name: "dev.catalogue.MONGO_URL", value: "mongodb://mongodb-dev.chandupcs.online:27017/catalogue" }
        - {name: "dev.frontend.CATALOGUE_URL", value: "http://catalogue-dev.chandupcs.online:80/" }
        - {name: "dev.frontend.CART_URL", value: "http://cart-dev.chandupcs.online:80/" }
        - {name: "dev.frontend.USER_URL", value: "http://user-dev.chandupcs.online:80/" }
        - {name: "dev.frontend.PAYMENT_URL", value: "http://payment-dev.chandupcs.online:80/" }
        - {name: "dev.frontend.SHIPPING_URL", value: "http://shipping-dev.chandupcs.online:80/" }
        - {name: "dev.payment.CART_HOST", value: "cart-dev.chandupcs.online" }
        - {name: "dev.payment.USER_HOST", value: "user-dev.chandupcs.online" }
        - {name: "dev.payment.CART_PORT", value: "80" }
        - {name: "dev.payment.USER_PORT", value: "80" }
        - {name: "dev.payment.AMQP_HOST", value: "rabbitmq-dev.chandupcs.online" }
        - {name: "dev.payment.AMQP_USER", value: "roboshop" }
        - {name: "dev.shipping.CART_ENDPOINT", value: "cart-dev.chandupcs.online:80" }
        - {name: "dev.shipping.DB_HOST", value: "mysql-dev.chandupcs.online" }
        - {name: "dev.user.MONGO", value: "true" }
        - {name: "dev.user.MONGO_URL", value: "mongodb://mongodb-dev.chandupcs.online:27017/users" }
        - {name: "dev.user.REDIS_HOST", value: "redis-dev.chandupcs.online" }
        - { name: "dev.cart.app_version", value: "1.2.0" }
        - { name: "dev.catalogue.app_version", value: "1.0.3" }
        - { name: "dev.frontend.app_version", value: "0.0.0" }
        - { name: "dev.user.app_version", value: "1.2.0" }
        - { name: "dev.shipping.app_version", value: "1.1.0" }
        - { name: "dev.payment.app_version", value: "0.0.0" }


          
          
          
          
### prod for mutable and immutable approach
#        - { name: "prod.cart.REDIS_HOST", value: "redis-prod.chandupcs.online" }
#        - { name: "prod.cart.CATALOGUE_HOST", value: "catalogue-prod.chandupcs.online" }
#        - { name: "prod.cart.CATALOGUE_PORT", value: "80" }
#        - { name: "prod.catalogue.MONGO", value: "true" }
#        - { name: "prod.catalogue.MONGO_URL", value: "mongodb://mongodb-prod.chandupcs.online:27017/catalogue" }
#        - { name: "prod.frontend.CATALOGUE_URL", value: "http://catalogue-prod.chandupcs.online:80/" }
#        - { name: "prod.frontend.CART_URL", value: "http://cart-prod.chandupcs.online:80/" }
#        - { name: "prod.frontend.USER_URL", value: "http://user-prod.chandupcs.online:80/" }
#        - { name: "prod.frontend.PAYMENT_URL", value: "http://payment-prod.chandupcs.online:80/" }
#        - { name: "prod.frontend.SHIPPING_URL", value: "http://shipping-prod.chandupcs.online:80/" }
#        - { name: "prod.payment.CART_HOST", value: "cart-prod.chandupcs.online" }
#        - { name: "prod.payment.USER_HOST", value: "user-prod.chandupcs.online" }
#        - { name: "prod.payment.CART_PORT", value: "80" }
#        - { name: "prod.payment.USER_PORT", value: "80" }
#        - { name: "prod.payment.AMQP_HOST", value: "rabbitmq-prod.chandupcs.online" }
#        - { name: "prod.payment.AMQP_USER", value: "roboshop" }
#        - { name: "prod.shipping.CART_ENDPOINT", value: "cart-prod.chandupcs.online:80" }
#        - { name: "prod.shipping.DB_HOST", value: "mysql-prod.chandupcs.online" }
#        - { name: "prod.user.MONGO", value: "true" }
#        - { name: "prod.user.MONGO_URL", value: "mongodb://mongodb-prod.chandupcs.online:27017/users" }
#        - { name: "prod.user.REDIS_HOST", value: "redis-prod.chandupcs.online" }
#        - { name: "prod.cart.app_version", value: "1.2.0" }
#        - { name: "prod.catalogue.app_version", value: "1.0.3" }
#        - { name: "prod.frontend.app_version", value: "0.0.0" }
#        - { name: "prod.user.app_version", value: "1.2.0" }
#        - { name: "prod.shipping.app_version", value: "1.1.0" }
#        - { name: "prod.payment.app_version", value: "0.0.0" }


# PROD for kubernetes
        - { name: "prod.cart.REDIS_HOST", value: "prod-elasti-cache-cluster.mlcbvd.0001.use1.cache.amazonaws.com" }
        - { name: "prod.cart.CATALOGUE_HOST", value: "catalogue-roboshop" }
        - { name: "prod.cart.CATALOGUE_PORT", value: "8080" }

        - { name: "prod.catalogue.DOCUMENTDB", value: "true" }
        - { name: "prod.catalogue.DOCUMENTDB_USER", value: "docdb1" }
        - { name: "prod.catalogue.DOCUMENTDB_PASS", value: "Roboshop" }
        - { name: "prod.catalogue.DOCUMENTDB_ENDPOINT", value: "prod-docdb-cluster-instance-1.crgf39vwmbxk.us-east-1.docdb.amazonaws.com:27017" }
        - { name: "prod.catalogue.MONGO_URL", value: "mongodb://docdb1:Roboshop@prod-docdb-cluster.cluster-crgf39vwmbxk.us-east-1.docdb.amazonaws.com:27017/?ssl=true&ssl_ca_certs=us-east-1-bundle.pem&replicaSet=rs0&readPreference=secondaryPreferred&retryWrites=false" }

        - { name: "prod.user.DOCUMENTDB", value: "true" }
        - { name: "prod.user.DOCUMENTDB_USER", value: "docdb1" }
        - { name: "prod.user.DOCUMENTDB_PASS", value: "Roboshop" }
        - { name: "prod.user.REDIS_HOST", value: "prod-elasti-cache-cluster.mlcbvd.0001.use1.cache.amazonaws.com" }
        - { name: "prod.user.MONGO_URL", value: "mongodb://docdb1:Roboshop@prod-docdb-cluster.cluster-crgf39vwmbxk.us-east-1.docdb.amazonaws.com:27017/?ssl=true&ssl_ca_certs=us-east-1-bundle.pem&replicaSet=rs0&readPreference=secondaryPreferred&retryWrites=false" }
        - { name: "prod.user.DOCUMENTDB_ENDPOINT", value: "prod-docdb-cluster-instance-1.crgf39vwmbxk.us-east-1.docdb.amazonaws.com:27017" }

        - { name: "prod.frontend.CATALOGUE_URL", value: "http://catalogue-prod.chandupcs.online:80/" }
        - { name: "prod.frontend.CART_URL", value: "http://cart-prod.chandupcs.online:80/" }
        - { name: "prod.frontend.USER_URL", value: "http://user-prod.chandupcs.online:80/" }
        - { name: "prod.frontend.PAYMENT_URL", value: "http://payment-prod.chandupcs.online:80/" }
        - { name: "prod.frontend.SHIPPING_URL", value: "http://shipping-prod.chandupcs.online:80/" }

        - { name: "prod.payment.CART_HOST", value: "cart-roboshop" }
        - { name: "prod.payment.USER_HOST", value: "user-roboshop" }
        - { name: "prod.payment.CART_PORT", value: "8080" }
        - { name: "prod.payment.USER_PORT", value: "8080" }
        - { name: "prod.payment.AMQP_HOST", value: "rabbitmq-prod.chandupcs.online" }
        - { name: "prod.payment.AMQP_USER", value: "roboshop" }

        - { name: "prod.shipping.CART_ENDPOINT", value: "cart-roboshop:8080" }
        - { name: "prod.shipping.DB_HOST", value: "prod-rds-cluster.cluster-crgf39vwmbxk.us-east-1.rds.amazonaws.com" }
        - { name: "prod.shipping.DB_PASS", value: "Roboshop" }
        - { name: "prod.shipping.DB_USER", value: "rds1" }





        ### PASSWORDS SHOULD NEVER BE KEPT IN THESE REPOS, THOSE SHOULD BE CREATED MAUALLY, BUT FOR LAB PURPOSE IAM CREATING HERE
    - name: Create Secrets
      community.aws.aws_ssm_parameter_store:
        name: "{{ item.name }}"
        value: "{{ item.value }}"
        region: us-east-1
        string_type: "SecureString"
      loop:
        - {name: "dev.payment.AMQP_PASS", value: "roboshop123" }
        - {name: "dev.rabbitmq.AMQP_PASS", value: "roboshop123" }
        - {name: "dev.docdb.DB_ADMIN_USER", value: "docdb1" }
        - {name: "dev.docdb.DB_ADMIN_PASS", value: "Roboshop" }
        - {name: "dev.rds.DB_ADMIN_USER", value: "rds1" }
        - {name: "dev.rds.DB_ADMIN_PASS", value: "Roboshop" }
        - {name: "dev.rabbitmq.DB_ADMIN_USER", value: "rabbitmq112345" }
        - {name: "dev.rabbitmq.DB_ADMIN_PASS", value: "Roboshop@123456" }
        - {name: "nexus.user", value: "admin" }
        - {name: "nexus.pass", value: "admin123" }
        - {name: "grafana.api_key", value: "eyJrIjoiUHBncjVXd0Q2ZDd3MDhoTnZzeVlkWmp3SjZDZUlGRzgiLCJuIjoiY2xpIiwiaWQiOjF9" }
        - {name: "ses.user", value: "AKIATZX7HJG6PETLQVUS" }
        - {name: "ses.pass", value: "BEd/hB7UeM3jQEUp9j9PVk/QNP81DaLWFWTSWUdOJOiA" }
        - {name: "dev-SSH.user", value: "root" }
        - {name: "dev-SSH.pass", value: "DevOps321" }
        - { name: "sonarqube.user", value: "admin" }
        - { name: "sonarqube.pass", value: "admin123" }

###prod
        - { name: "prod.payment.AMQP_PASS", value: "roboshop123" }
        - { name: "prod.rabbitmq.AMQP_PASS", value: "roboshop123" }
        - { name: "prod.docdb.DB_ADMIN_USER", value: "docdb1" }
        - { name: "prod.docdb.DB_ADMIN_PASS", value: "Roboshop" }
        - { name: "prod.rds.DB_ADMIN_USER", value: "rds1" }
        - { name: "prod.rds.DB_ADMIN_PASS", value: "Roboshop" }
        - { name: "prod.rabbitmq.DB_ADMIN_USER", value: "rabbitmq112345" }
        - { name: "prod.rabbitmq.DB_ADMIN_PASS", value: "Roboshop@123456" }
        - { name: "nexus.user", value: "admin" }
        - { name: "nexus.pass", value: "admin123" }
        - { name: "grafana.api_key", value: "eyJrIjoiUHBncjVXd0Q2ZDd3MDhoTnZzeVlkWmp3SjZDZUlGRzgiLCJuIjoiY2xpIiwiaWQiOjF9" }
        - { name: "ses.user", value: "AKIATZX7HJG6PETLQVUS" }
        - { name: "ses.pass", value: "BEd/hB7UeM3jQEUp9j9PVk/QNP81DaLWFWTSWUdOJOiA" }
        - { name: "prod-SSH.user", value: "root" }
        - { name: "prod-SSH.pass", value: "DevOps321" }



