
- name: Configure YUM erlag and rabbitmq server Repos from the script provided by vendor
  ansible.builtin.shell: curl -s {{ item }} |  bash
  loop:
    - https://packagecloud.io/install/repositories/rabbitmq/erlang/script.rpm.sh
    - https://packagecloud.io/install/repositories/rabbitmq/rabbitmq-server/script.rpm.sh

- name: Installing erlang & rabbitmq-server
  ansible.builtin.yum:
    name:
#    - erlang  //as rabbitmq-server itself installing the erlang-26.0 so no need separately from 18/05/23 this issue happening
    - rabbitmq-server
    state: installed


- name: Start service rabbitmq-server
  ansible.builtin.systemd:
    name: rabbitmq-server
    state: restarted
    enabled: yes

- name: add application user roboshop and give priv & make admin
  community.rabbitmq.rabbitmq_user:
    user: roboshop
    password: "{{rabbitmq_roboshop_password}}"
    vhost: /
    configure_priv: .*
    read_priv: .*
    write_priv: .*
    state: present
    tags: administrator
  vars:
    rabbitmq_roboshop_password: "{{ lookup('aws_ssm', '{{env}}.{{component}}.AMQP_PASS', region='us-east-1' ) }}"

