- name: set_up server
  ansible.builtin.include_tasks: "server.yml"
  when: prometheus == "server"

- name: set_up exporter
  ansible.builtin.include_tasks: "exporter.yml"
  when: prometheus == "exporter"