- name: Copy Prometheus Config
  ansible.builtin.template:
    src: prometheus.yml
    dest: /opt/prometheus/prometheus.yml
  vars:
    labels:
      - { tag: "env", label: "environment" }
      - { tag: "Name", label: "name" }

- name : copy record rules file
  ansible.builtin.template:
    src: record_rules.yml
    dest:  /opt/prometheus/record_rules.yml
    remote_src: yes

- name : copy alert rules file
  ansible.builtin.template:
    src: alert-rules.yml
    dest:  /opt/prometheus/alert-rules.yml
    remote_src: yes

- name: Restart Prometheus
  ansible.builtin.systemd:
    name: prometheus
    state: restarted

- name: check whether prometheus  started or not
  ansible.builtin.shell: netstat -lntp | grep 9090


- name : copy alert-manager file
  ansible.builtin.template:
    src: alertmanager.yml
    dest:  /opt/alertmanager/alertmanager.yml
    remote_src: yes

- name: Restart Alert-manager
  ansible.builtin.systemd:
    name: alertmanager
    state: restarted

- name: check whether alertmanager  started or not
  ansible.builtin.shell: netstat -lntp | grep 9093


## grafana given in meta file

