- name: set hostname
  ansible.builtin.shell: set-hostname {{component}}

- name: install  prometheus node exporter
  ansible.builtin.shell: sudo labauto prometheus-node-exporter

- name: setup prometheus alert config file
  ansible.builtin.template:
    src: alert.yml
    dest: /tmp/alert.yml

- name: Copy Prometheus Alerts Configuration to Prometheus Server
  ansible.builtin.shell: sshpass -p {{ lookup('aws_ssm', '{{env}}-SSH.pass', region='us-east-1' ) }} scp /tmp/alert.yml {{ lookup('aws_ssm', '{{env}}-SSH.user', region='us-east-1' ) }}@172.31.0.51:/opt/prometheus/alerts/{{component}}.yml

- name: reload  prometheus server
  ansible.builtin.shell: curl -v -s -XPOST http://172.31.0.51:9090/-/reload


- name: import ELK
  ansible.builtin.import_role:
   name: elk



## grafana dashboard for graphs
- name : make a template
  ansible.builtin.template:
    src: grafana-template.json
    dest:  /tmp/grafana.json
    remote_src: yes


- name: Import Grafana dashboard
  community.grafana.grafana_dashboard:
    grafana_url: http://44.212.47.149:3000
    grafana_api_key: "{{ lookup('aws_ssm', 'grafana.api_key', region='us-east-1' ) }}"
    state: present
    overwrite: yes
    path: /tmp/grafana.json