- name: set hostname
  ansible.builtin.shell: set-hostname {{component}}

- name: install  prometheus node exporter
  ansible.builtin.shell: sudo labauto prometheus-node-exporter

- name: setup prometheus alert config file
  ansible.builtin.template:
    src: alert.yml
    dest: /tmp/alert.yml

## grafana
- name : make a template
  ansible.builtin.template:
    src: grafana-template.json
    dest:  /tmp/grafana.json
    remote_src: yes


- name: Import Grafana dashboard
  community.grafana.grafana_dashboard:
    grafana_url: http://44.197.175.35:3000
    grafana_api_key: "{{ lookup('aws_ssm', 'grafana.api_key', region='us-east-1' ) }}"
    state: present
    overwrite: yes
    path: /tmp/grafana.json