
- name: Install mysql & python3-PyMySQL
  ansible.builtin.yum:
    name:
     - python3-PyMySQL
     - mysql
    state: installed

- name: Load mysql Schema
  ansible.builtin.shell: mysql --host mysql-dev.chandupcs.online -uroot -p{{root_mysql_password}} </app/schema/{{component}}.sql

- name: Start {{component}} Service
  ansible.builtin.systemd:
    name: "{{component}}"
    state: restarted