
- name: Install mysql
  ansible.builtin.yum:
    name:
     - python3-PyMySQL
     - mysql
    state: installed

- name: Load Schema
  ansible.builtin.shell: mysql --host mysql-dev.chandupcs.online -uroot -p{{root_mysql_password}} </app/schema/{{component}}.sql

- name: Start {{component}} Service
  ansible.builtin.systemd:
    name: "{{component}}"
    daemon_reload: yes
    enabled: yes
    state: restarted