
- name: Install mysql & python3-PyMySQL
  ansible.builtin.yum:
    name:
     - python3-PyMySQL
     - mysql
    state: installed


- name: load mysql schema
  ansible.builtin.shell: mysql -h {{ lookup('aws_ssm', '{{env}}.rds.endpoint', region='us-east-1' ) }} -u{{ lookup('aws_ssm', '{{env}}.rds.DB_ADMIN_USER', region='us-east-1' ) }} -p{{ lookup('aws_ssm', '{{env}}.rds.DB_ADMIN_PASS', region='us-east-1' ) }} </app/schema/{{component}}.sql
#    state: import
#    name: all
#    target: /app/schema/{{component}}.sql
#    login_host:  "{{ lookup('aws_ssm', '{{env}}.rds.endpoint', region='us-east-1' ) }}"
#    login_user: "{{ lookup('aws_ssm', '{{env}}.rds.DB_ADMIN_USER', region='us-east-1' ) }}"
#    login_password: "{{ lookup('aws_ssm', '{{env}}.rds.DB_ADMIN_PASS', region='us-east-1' ) }}"


- name: REStart {{component}} Service
  ansible.builtin.systemd:
    name: "{{component}}"
    state: restarted