
- name: Install mysql & python3-PyMySQL
  ansible.builtin.yum:
    name:
     - python3-PyMySQL
     - mysql
    state: installed


- name: load mysql schema
  community.mysql.mysql_db:
    state: import
    name: all
    target: /app/schema/{{component}}.sql
    login_host: mysql-dev.chandupcs.online
    login_user: "{{ mysql_user }}"
    login_password: "{{ root_mysql_password }}"
  vars:
    mysql_user: "{{ lookup('aws_ssm', '{{env}}.mysql.DB_ADMIN_USER', region='us-east-1' ) }}"
    root_mysql_password: "{{ lookup('aws_ssm', '{{env}}.mysql.DB_ADMIN_PASS', region='us-east-1' ) }}"


- name: REStart {{component}} Service
  ansible.builtin.systemd:
    name: "{{component}}"
    state: restarted