- name: Configure NodeJS repos
  ansible.builtin.shell: curl -sL https://rpm.nodesource.com/setup_lts.x | bash

- name: Install NodeJS
  ansible.builtin.yum:
    name: nodejs
    state: installed

- name: include app_pre_req file
  ansible.builtin.include_tasks: app_pre_req.yml

- name: dowloading the docdb pem file
  ansible.builtin.get_url:
    url: https://s3.amazonaws.com/rds-downloads/rds-combined-ca-bundle.pem
    dest: /app/rds-combined-ca-bundle.pem
  when: schema_load

- name: Install Nodejs dependencies
  community.general.npm:
    path: /app
    state: latest

- name: include systemd file
  ansible.builtin.include_tasks: "systemd.yml"

- name: load schema
  ansible.builtin.include_tasks: "{{schema_type}}_schema.yml"
  when: schema_load
