- name: install python,gcc and python3-devel
  ansible.builtin.yum:
     name:
     - python36
     - gcc
     - python3-devel
     state: installed

- name: include app_pre_req file
  ansible.builtin.include_tasks: "app_pre_req.yml"


- name: Install specified python requirements
  ansible.builtin.pip:
    requirements: /app/requirements.txt
    executable: pip3.6


- name: include systemd file
  ansible.builtin.include_tasks: "systemd.yml"